services:
  #  tun:
  #    build:
  #      context: ./goxray
  #    working_dir: /app
  #    cap_add:
  #      - NET_ADMIN
  #    devices:
  #      - /dev/net/tun:/dev/net/tun
  #    networks:
  #      - vpn_net
  #    restart: unless-stopped
  #    environment:
  #      - XRAY_CONFIG_URL=${VLESS_LINK}

  bot:
    build:
      context: ./bot
    working_dir: /app
    command: >
      uv run watchmedo auto-restart --pattern="*.py,.env" --recursive -- python src/main.py
    restart: always
    #network_mode: "service:tun"
    #depends_on:
    #  - tun
    volumes:
      - bot_data:/app/data
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - DATABASE_URL=${DATABASE_URL}
    develop:
      watch:
        - action: sync
          path: ./bot
          target: /app
          ignore:
            - .venv/
            - __pycache__/
        - action: rebuild
          path: ./bot/uv.lock

  server:
    build:
      context: ./server
    working_dir: /app
    restart: unless-stopped
    #network_mode: "service:tun"
    #depends_on:
    #  - tun

#networks:
#  vpn_net:
#    driver: bridge

volumes:
  bot_data:
