FROM golang:1.24-alpine AS builder
ENV CGO_ENABLED=0 \
    GOOS=linux
WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN go build -ldflags "-s -w" -o server main.go

FROM alpine:latest
RUN apk update && apk add --no-cache ca-certificates
WORKDIR /app
COPY --from=builder /app/server .
EXPOSE 9865
CMD ["./server"]